(include_subdirs unqualified)

(library
 (name charr)
 (modules
  debug
  io
  env
  cfg
  lexer
  lexer_pp
  parser
  ctype
  ast
  ast_resolution
  ast_flow_label
  ast_type_check
  irgen
  passes
  constant_folding
  copy_propagation
  dead_store_elimination
  unreachable_code_elimination
  ir
  codegen
  codegen_lower
  codegen_fixup
  asm
  asm_symtab
  emit)
 (preprocess
  (pps ppx_deriving.show ppx_deriving.ord ppx_deriving.eq)))

(menhir
 (modules parser))

(ocamllex lexer)
